index.php
=> test-prueba

index.php
=> Crear rama

index.php
=> arreglo input index.php

repository/validar.php
=> arreglo conexion

repository/locadidad.php, repository/registro_usuario.php, repository/validar.php, views/Registro.php
=> agragacion de la localidad

repository/locadidad.php, repository/tipo_documento.php, views/Registro.php
=> Numero documento

index.php, repository/localidad.php, repository/registro_usuario.php, repository/tipo_documento.php, repository/validar.php, views/Nosotros.php, views/admin/pag_inicio.php
Agregacion de roles, correxion de errores en el encarpetamiento
=> Agregacion de roles, correxion de errores en el encarpetamiento

useCase/logOut.php, views/admin/pag_inicio.php, views/pag_inicio.php
=> Cerrar sesion o Destruir esta

views/styles/Estilos1.css
=> Arreglo en Estilo1

views/styles/Estilos1.css
=> Actualizar

repository/registro_usuario.php, views/admin/crearUsuario.php
=> Correccion en registro

index.php, views/Nosotros.php, views/session/Registro.php, views/styles/Estilos.css, views/styles/Estilos3.css, views/styles/quienessomo.css
=> No duplicacion

views/admin/paginaInicio.php, views/gerente/gerente.php, views/gerente/paginaInicio.php, views/gerente/servicios.php, views/styles/Estilos4.css, views/styles/Estilos5.css, views/styles/Estilos6.css
Agregacion de trabajos de sebastian y camilo, toca corregir los encarpetamientos y arreglar otras cosas a demas de esto toca agregar bien el back
=> Agregacion de trabajos de sebastian y camilo, toca corregir los encarpetamientos y arreglar otras cosas a demas de esto toca agregar bien el back

views/cliente/agendar_cita.php, views/cliente/form_agendar_cita.php
=> cambios de cita

repository/registro_usuario.php, repository/validar.php, views/admin/paginaInicio.php, views/gerente/paginaInicio.php, views/session/Registro.php, views/session/sesion.php
Arreglo con la carpeta gerente, cambio en base de datos y arreglo en el Registro, toca arreglar el registrar usuario
=> Arreglo con la carpeta gerente, cambio en base de datos y arreglo en el Registro, toca arreglar el registrar usuario

index.php, repository/registro_usuario.php, views/session/Registro.php
El registro ya sirve correctamente
=> El registro ya sirve correctamente

repository/contra.php, views/perfil/recuperarContra.php
=> Agregue el cambiar contraseña

views/cliente/form_agendar_cita.php, views/cliente/nosotros.php, views/gerente/agg_servicios.php, views/gerente/insertar_servicios.php
arreglo pequeños detalles y la funcionabilidad de agg servicios
=> arreglo pequeños detalles y la funcionabilidad de agg servicios

index.php, views/admin/admin_panel.php, views/admin/ver_aprobados.php, views/admin/ver_rechazados.php, views/cliente/paginaInicio.php, views/cliente/soli_gerente.php, views/gerente/paginaInicio.php, views/styles/Estilos9.css
=> arreglos de ultimo momento

views/admin/admin_autolavados.php, views/admin/paginaInicio.php, views/admin/procesar_autolavado.php, views/admin/public_map.php, views/cliente/Mapa.php, views/styles/estilomapa.css
autolavados y mapas completado
=> autolavados y mapas completado

index.php, views/cliente/paginaInicio.php
Agregue espacios responsivos para los estilos html y css pero hay mas temas a corregir y agregue iconos.
=> Nuevos iconos y espacios responsivos

repository/contra.php
=> Agregar contra

index.php, views/admin/admin_autolavados.php, views/styles/adminatuolavados.css
crear estilo en admin autolavados
=> crear estilo en admin autolavados

repository/contraseñacambiada.php, repository/validar.php, views/cliente/Mapa.php, views/cliente/agendar_cita.php, views/cliente/form_agendar_cita.php, views/cliente/nosotros.php, views/cliente/paginaInicio.php, views/cliente/perfil.php, views/cliente/proseso_cam_rol.php, views/cliente/soli_gerente.php, views/cliente/subir_foto.php, views/perfil/cambiarcontraperfil.php, views/styles/estilomapa.css, views/styles/modalperfil.css
Agregue nuevas carpetas y nuevos archivos organice algunos CSS y tambien ya funciona el cambiar contraseña
=> Agregue nuevas carpetas y nuevos archivos organice algunos CSS y tambien ya funciona el cambiar contraseña

views/admin/admin_panel.php, views/admin/public_map.php
=> modificar estilos de admin

views/cliente/paginaInicio.php, views/cliente/soli_gerente.php, views/cliente/terminos.php, views/styles/Estilos9.css, views/styles/modalperfil.css
=> arreglos pequeños de frontend

recibos/Itadori_Yuji/Recibo_Reserva_6.txt, recibos/noke_ramirez/Recibo_Reserva_7.txt, views/cliente/paginaInicio.php, views/cliente/terminos.php, views/cliente/ver_recibo.php, views/cliente/ver_recibos.php, views/gerente/actualizar_terminado.php, views/gerente/citas_aprobadas.php, views/gerente/enviar_recibo.php, views/gerente/ver_recibo.php, views/recibos/usuario_19/Recibo_Reserva_7.txt
añado todo sobre recibos usuario y gerente
=> añado todo sobre recibos usuario y gerente

views/admin/admin_autolavados.php, views/gerente/agg_servicios.php, views/gerente/citas_pendientes.php, views/perfil/cambiarcontraAdmin.php, views/perfil/cambiarcontragerente.php, views/styles/Estilos8.css, views/styles/citaspendientes.css
=> cambios Sebastian y Camilo

repository/reseñaCliente.php, views/cliente/paginaInicio.php, views/cliente/resena.php
Ya sirven las reseñas faltan arreglos pero ya funciona
=> Ya sirven las reseñas faltan arreglos pero ya funciona

views/cliente/terminos.php, views/cliente/ver_recibos.php, views/styles/verRecibos.css
=> Arreglo de estilos en recibos

index.php
=> cambios en el logo e index

views/admin/paginaInicio.php, views/admin/public_map.php
=> administrador

repository/registro_usuario.php, views/admin/paginaInicio.php, views/admin/public_map.php, views/perfil/cambiarcontraAdmin.php, views/session/Registro.php, views/styles/admin.css, views/styles/cambiarContra.css, views/styles/publicMap.css
Arreglo en los estilos correccion en estos y agregar nuevos
=> Arreglo en los estilos correccion en estos y agregar nuevos

views/cliente/form_agendar_cita.php, views/cliente/obtener_servicios.php, views/gerente/citas_pendientes.php
=> arreglos de mapa precio

views/admin/admin_autolavados.php, views/admin/crearUsuario.php, views/admin/public_map.php, views/admin/ver_aprobados.php, views/admin/ver_rechazados.php, views/cliente/Mapa.php, views/cliente/resena.php, views/cliente/ver_recibo.php, views/gerente/citas_aprobadas.php, views/styles/aprobados.css, views/styles/citas_aprobadas.css, views/styles/resena.css
ya casi vamos terminando los estilos
=> ya casi vamos terminando los estilos

views/gerente/agg_servicios.php, views/gerente/citas_pendientes.php
=> cambios de mensajes en blanco

repository/validar.php, views/cliente/resena.php, views/perfil/cambiarcontraperfil.php, views/session/sesion.php, views/styles/Estilos1.css
=> estilos de perfil

views/gerente/paginaInicio.php, views/styles/paginaInicioGerente.css
=> arreglo gerenet

views/admin/perfil.php, views/admin/public_map.php, views/cliente/perfil.php, views/gerente/perfil.php, views/styles/adm_panel.css, views/styles/estilosesion.css, views/styles/publicMap.css
=> Mas footer

repository/validar.php, views/session/sesion.php
=> Contraseña hasheada

views/cliente/soli_gerente.php, views/gerente/agg_servicios.php, views/gerente/exito.php, views/gerente/insertar_servicios.php, views/gerente/regist_autol.php, views/gerente/registro_autolavado.php
=> cambios sencillo

views/gerente/perfil_autol.php
=> arregloboton

views/gerente/agg_servicios.php, views/gerente/citas_pendientes.php, views/gerente/insertar_servicios.php
agregar citas completado falta estilos
=> agregar citas completado falta estilos

views/gerente/regist_autol.php, views/gerente/registro_autolavado.php
arreglo el mensaje de registro_autolavado
=> arreglo el mensaje de registro_autolavado
